### ISSUE TITLE
Participant is logged out if the intervire page is refreshed

### ISSUE THREAD

**Issue by kazoompa** [obiba/amber-visit#4]
- Start an interview as a manager or participant
- Refresh the page

The user is logout and routed to the login page

**Comment by meek0** [comment]
Two thing need to be done:
- persist auth store using `{ persist: true }` that way the manager will stay loggedin until `reAuthenticate` call fails or logout is called
- persist the participant's cred that way the participant's api calls will continue to work until logout

**Comment by ymarcon** [comment]
Great fix, thanks!
